// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afzvzuvsjzxfvwlgqdtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmenZ6dXZzanp4ZnZ3bGdxZHR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDczNjgsImV4cCI6MjA3MDYyMzM2OH0.hCP_6ChTuO9XREIs6DR92ekle6QpzK9Kd-bXVc09JrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});